name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest ]

    timeout-minutes: 120
    environment:
      name: pypi
      url: https://pypi.org/p/capstone6pwndbg
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing on pypi
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v7

      - name: build & publish
        run: |
          git submodule update --init --recursive
          cd ./capstone && git apply ../python-rename.patch && cd ..
          
          cd ./capstone/bindings/python
          uv run --with cibuildwheel==3.3.1 cibuildwheel --output-dir dist

  sdist:
    name: Build source distribution
    runs-on: ubuntu-24.04-arm
    environment:
      name: pypi
      url: https://pypi.org/p/capstone6pwndbg
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing on pypi
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v7

      - name: build & publish
        run: |
          git submodule update --init --recursive
          cd ./capstone && git apply ../python-rename.patch && cd ..
          
          cd ./capstone/bindings/python
          uv build --sdist
          uv publish
